name: Build Image
on:
  push:
    paths:
      - 'server/**'
      - '.forgejo/workflows/server.yaml'
    branches:
      - main

env:
  IMAGE_NAME: git.jackz.me/${{ github.repository_owner }}/translate-server

jobs:
  build:
    runs-on: ubuntu-full
    steps:
      - name: Checkout
        uses: https://git.jackz.me/actions/checkout@v4
      - name: Login to Container Registry
        uses: https://git.jackz.me/actions/docker-login-action@v3
        with:
          registry: git.jackz.me
          username: ${{ github.repository_owner }}
          password: ${{ secrets.REGISTRY_TOKEN }}
      - name: Set up Docker Buildx
        uses: https://git.jackz.me/actions/docker-setup-buildx-action@v3
      # replace / with - for tag
      - name: Set ENV
        run: echo "TAG=${FORGEJO_REF_NAME////-}" >> "$GITHUB_ENV"
      - name: Build and push
        uses: https://git.jackz.me/actions/docker-build-push-action@v6
        with:
          context: server
          file: server/Dockerfile
          push: true
          cache-from: type=registry,ref=${{ env.IMAGE_NAME }}:buildcache
          cache-to: type=registry,ref=${{ env.IMAGE_NAME }}:buildcache,mode=max
          tags: ${{ env.IMAGE_NAME }}:${{ env.TAG }}
